### Site Settings ###
site_name: Flipper Community Wiki
site_url: https://flipper.wiki
repo_name: Flipper Community Wiki
repo_url: https://github.com/Flipper-Community/flipper-community-wiki
site_description: Flipper Zero Unofficial Community Wiki
site_author: Flipwiki Unofficial Community


### Theme settings ###
theme:
  name: material
  logo: assets/images/white_dolph_transparent.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to Light Mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Auto

extra_css:
  - stylesheets/extra.css


### Copyright footer info ###
copyright: The content of this wiki is created and maintained by the community and does not represent the official views, statements, or endorsements of Flipper Devices.
  <div>All Flipper artwork is attributed to <a href="https://flipperdevices.com">Flipper Devices</a> unless otherwise stated. 
  <div>All trademarks are the property of their respective owners and are used in this document for descriptive purposes only, without any intention of infringement.

### Plugin loading
# plugins:
#### social plugin disabled for now, revisit if the free version ever gets better customizability
#   - social:


### MkDoc extension loading ###
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true


### Navigation Heirarchy ###
### Add your .md files in this section ###
nav:
  - Home: index.md

  - Getting Started:
     - The Basics: getting-started.md
     - FAQ: faq-general.md
     - Troubleshooting: troubleshooting.md

  - Subsystems:
    - 125 KHz RFID:
      - Overview: 125khz-rfid-overview.md
    - BadUSB:
      - Overview: badusb-overview.md
    - NFC:
      - Overview: nfc-overview.md
      - MIFARE Classic: mifareclassic.md
      - Arcade Cards: arcadecards.md
      - Public Transport: publictransport.md
    - SubGHz:
      - Overview: subghz-overview.md
    - GPIO: 
      - Overview: gpio-overview.md
      - Wi-Fi Devboard: wifi-devboard.md

  - Development:
    - Firmware:
      - Overview: development-overview.md
    - Javascript:
      - Overview: javascript-overview.md

  - Guides & Tutorials:
    - Development:
      - Designing Custom Fonts: tutorials/f0_fonts_guide/guide.md

  - Site Info:
    - About: about.md
    - Contributing: contributing.md
    - Report An Issue!: 'https://github.com/Flipper-Community/flipper-community-wiki/issues'
