### Site Settings ###
site_name: Flipper Community Wiki
site_description: Project documentation with Markdown.
site_author: Flipper Community

### Theme settings ###
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to Light Mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Auto



### Copyright footer info ###
copyright: All Flipper artwork is attributed to <a href="https://flipperdevices.com">Flipper Devices</a> unless otherwise stated. 
  <div>All trademarks are the property of their respective owners and are used in this document for descriptive purposes only, without any intention of infringement.


### MkDoc extension loading ###
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true


### Navigation Heirarchy ###
### Add your .md files in this section ###
nav:
  - Getting Started:
     - The Basics: getting-started.md

  - Subsystems:
    - NFC:
      - Overview: nfc.md
      - Arcade Cards: arcadecards.md
      - Public Transport: publictransport.md
    - 125 KHz RFID:
      - Overview: 125khz-rfid.md

  - Site Info:
    - About: about.md
    - Contributing: contributing.md
    - Github: 'https://github.com/Flipper-Community/flipper-community-wiki'

